name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          cmake -S. -Bbuild
          cmake --build build --parallel 8

      - name: Run tests
        run: ./build/main
